[package]
name = "embassy-ieee802154"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Embassy binding for IEEE802.15.4 MAC layer implementations"
keywords = ["embedded", "async", "dot15d4"]
categories = ["embedded", "ieee802.15.4", "MAC layer", "no-std", "asynchronous"]
repository = "https://github.com/embassy-rs/embassy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot15d4 = { git = "https://github.com/jeremydub/dot15d4.git", branch = "tsch-milestone1", default-features = false }
# dot15d4 = { path = "../../dot15d4-management-v2/dot15d4", default-features = false }
defmt = { version = "0.3", optional = true }
embassy-sync = { path = "../embassy-sync" }
embassy-net-driver = { path = "../embassy-net-driver" }
embedded-hal-async = { version = "1.0.0" }
rand_core = { version = "0.6.4", default-features = false }
static_cell = "2.0.0"

[features]
defmt = ["dep:defmt", "dot15d4/defmt"]
